<a href="https://colab.research.google.com/github/sojiseung/sjs0424/blob/main/m3_%EB%B6%84%EC%84%9D_%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC/05_27%EA%B3%BC%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Contents
 - 데이터 구조 Series, DataFrame
 - 인덱스, 생성, 선택, 추가, 변경, 삭제, 전치
 - 파이썬 자료형과 양방향 변환

#### 판다스
Pandas는 파이썬에서 데이터 분석 및 조작을 위한 강력하고 유연한 오픈 소스 라이브러리. Series와 DataFrame 같은 고수준의 데이터 구조를 제공하여, 복잡한 데이터 조작을 직관적이고 효율적으로 수행할 수 있게 한다.

[Pandas의 주요 역할과 기능]

* DataFrame과 Series: 2차원 테이블과 1차원 배열 형태의 데이터 구조를 제공
* 데이터 처리: 결측값 처리, 데이터 정제, 필터링, 병합, 연결 및 변환 등을 위한 다양한 기능을 제공
* 데이터 분석: 기술통계, 그룹화, 시계열 분석 등 복잡한 분석 작업을 제공
* 입출력 기능: CSV, Excel, SQL, JSON 등 다양한 파일 형식의 데이터를 읽고 쓸 수 있는 기능을 제공
* 시각화 지원: 매트플롯립과 연동하여 데이터 시각화가 가능하도록 제공
* 라이브러리는 여러 종류의 class와 다양한 내장 함수로 구성. 시리즈와 데이터프레임은 대표적인 클래스 객체임
* 시리즈 인덱스는 데이터 값과 일대일 대응. 파이썬 딕셔너리와 비슷한 구조. pandas.Series(딕셔너리)

In [2]:
# 시리즈 클래스 만들기
# pandas 불러오기 (pd)
import pandas as pd

# key:value 구조를 갖는 딕셔너리를 만들고 변수 dict_data에 저장
dict_data = {'a':1,'b':2,'c':3}

sr = pd.Series(dict_data)
print(sr)
type(sr)

a    1
b    2
c    3
dtype: int64


pandas.core.series.Series

In [5]:
# 리스트를 시리즈로 변환

list_data = ['2019-02-07',3.14,'ABC',100,True]
# sr = pd.Series(list_data,index=list('abcde'))
sr = pd.Series(list_data)
print(sr,type(sr))

0    2019-02-07
1          3.14
2           ABC
3           100
4          True
dtype: object <class 'pandas.core.series.Series'>


In [7]:
# 인덱스 및 값
idx = sr.index
val = sr.values
print(list(idx))
print(val)

[0, 1, 2, 3, 4]
['2019-02-07' 3.14 'ABC' 100 True]


In [15]:
# 튜플을 시리즈로 변환
tup_data = ('kevin', '2019-07-07','남',True)
#sr = pd.Series(tup_data)
#print(sr,type(sr))
#print('==========================')
sr = pd.Series(tup_data, index = ['이름', '생년월일','성별','학생여부'])
print(sr)

이름           kevin
생년월일    2019-07-07
성별               남
학생여부          True
dtype: object


In [34]:
sr = [1,2,3,4,5]
sr[1:3]

[2, 3]

In [19]:
# 인덱싱
print(sr[0])
print(sr['이름'])
print(sr[[1,2]])  # 시리즈에서 위치 기반 인덱싱을 사용해서 여러 요소를 선택 가능
# print(sr[1,2])  # 파이썬의 기본 인덱싱 방식으로 sr[1]과 같은 형태를 사용

kevin
kevin
생년월일    2019-07-07
성별               남
dtype: object


In [21]:
# 배열
import numpy as np

s1 = np.arange(11,21,2)
print(s1, type(s1))
print()
s2 = pd.Series(s1, index=list('abcde'))
print(s2, type(s2))

[11 13 15 17 19] <class 'numpy.ndarray'>

a    11
b    13
c    15
d    17
e    19
dtype: int64 <class 'pandas.core.series.Series'>


In [36]:
# Q. 배열을 생성후 시리즈로 변환하여 아래와 같이 출력하세요.
data = np.arange(1000, 5000, 1000)
state = ['Califonia','Ohio','Oregon','Texas']
obj = pd.Series(data, index=list(state))
obj.name = 'population'
obj.index.name = 'state'
print(obj)

state
Califonia    1000
Ohio         2000
Oregon       3000
Texas        4000
Name: population, dtype: int64


None과 np.nan의 차이점
- None은 파이썬의 내장형 객체로 주로 객체형 데이터에서 사용
- np.nan은 부동 소수점으로 취급되며 주로 숫자형 데이터에서 사용
- 연산 시 np.nan은 NaN 결과를 반환하는 반면 None은 TypeError를 발생시킨다.


In [37]:
obj.Califonia = np.nan
obj

state
Califonia       NaN
Ohio         2000.0
Oregon       3000.0
Texas        4000.0
Name: population, dtype: float64

In [39]:
null_mask = obj.isnull()
null_mask

state
Califonia     True
Ohio         False
Oregon       False
Texas        False
Name: population, dtype: bool

In [40]:
not_null_mask = obj.notnull()
not_null_mask

state
Califonia    False
Ohio          True
Oregon        True
Texas         True
Name: population, dtype: bool

In [41]:
filled_series = obj.fillna(0)
filled_series

state
Califonia       0.0
Ohio         2000.0
Oregon       3000.0
Texas        4000.0
Name: population, dtype: float64

In [42]:
obj.Califonia = np.nan
obj

state
Califonia       NaN
Ohio         2000.0
Oregon       3000.0
Texas        4000.0
Name: population, dtype: float64

In [43]:
obj.isnull().sum()

1

In [45]:
dropped_series = obj.dropna()
dropped_series

state
Ohio      2000.0
Oregon    3000.0
Texas     4000.0
Name: population, dtype: float64

In [47]:
dropped_series.isnull().sum()

0

In [48]:
# Series -> List
list_from_series = s2.tolist()
list_from_series

[11, 13, 15, 17, 19]

In [49]:
dict_from_series = s2.to_dict()
dict_from_series

{'a': 11, 'b': 13, 'c': 15, 'd': 17, 'e': 19}

In [50]:
df_from_series = s2.to_frame(name='Value')
df_from_series

Value
a     11
b     13
c     15
d     17
e     19

Q. 아래 시리즈에서 null값을 2개 입력 후 그 값을 0으로 대체 후 null값 여부를 확인한 후 출력하세요.

In [75]:
import pandas as pd
import numpy as np

# 1. Series 생성
s = pd.Series([5, 15, 25, 35, 45], index=['x','y','a','b','c'])
s.x = np.nan
s.y = np.nan
print('null 갯수 : ',s.isna().sum(),'\n')
s1 = s.fillna(0)
print('null 갯수 : ',s1.isna().sum(),'\n')
print(s1)

null 갯수 :  2 

null 갯수 :  0 

x     0.0
y     0.0
a    25.0
b    35.0
c    45.0
dtype: float64


Q. 주어진 리스트 [1, 2, 3, 4, 5]를 Pandas Series로 변환하고, 각 원소에 10을 더한 Series를 출력하세요.

In [77]:
import pandas as pd

# 주어진 리스트
data_list = [1, 2, 3, 4, 5]
index = ['a','b','c','d','e']

# pandas Series로 변환
series = pd.Series(data_list, index=(index))

# 각 원소에 10을 더한 Series
series_plus_10 = series + 10

# 결과출력
print('Original Series : ')
print(series)
print('\nSeries after adding 10 to each element : ')
print(series_plus_10)

Original Series : 
a    1
b    2
c    3
d    4
e    5
dtype: int64

Series after adding 10 to each element : 
a    11
b    12
c    13
d    14
e    15
dtype: int64


Q. Series [10, 20, 30, 40, 50]를 생성하고 인덱스를 ['a', 'b', 'c', 'd', 'e']로 설정하세요. 인덱스를 기준으로 Series를 정렬한 결과를 출력하세요.

In [64]:
import pandas as pd
d_list = [10,20,30,40,50]
dl = pd.Series(d_list, index=list('abcde'))
dl

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [78]:
import pandas as pd

# 주어진 데이터와 인덱스
data = [10,20,30,40,50]
index = ['a','b','c','d','e']

# Pandas Series 생성
series = pd.Series(data, index=(index))


AttributeError: 'Series' object has no attribute 'sort'

Q. Series ['a':1, 'b':2, 'c':3, 'd':4, 'e':5]에서 인덱스 'b', 'd'에 해당하는 원소를 선택하여 출력하세요.

In [68]:
import pandas as pd

# 주어진 데이터와 인덱스
data = [1, 2, 3, 4, 5]
index = ['a', 'b', 'c', 'd', 'e']
slist = pd.Series(data, index=list(index))
print(slist[['b','d']])

b    2
d    4
dtype: int64


In [79]:
import pandas as pd

# 주어진 데이터와 인덱스
data = [1,2,3,4,5]
index = ['a','b','c','d','e']

#panda Series 생성
series = pd.Series(data, index=index)

# 인덱스 'b'와 'd'에 해당하는 원소 선택
selected_elements = series[['b','d']]

print(selected_elements)

b    2
d    4
dtype: int64


#### 데이터프레임
* 데이터프레임은 2차원 배열. R의 데이터프레임에서 유래.
* 데이터프레임의 열은 각각 시리즈 개체.
* 시리즈를 열벡터라고 하면 데이터프레임은 여러개의 열벡터들이 같은 행 인덱스를
  기준으로 줄지어 결합된 2차원 벡터 또는 행렬.
* 선형대수학에서 열 벡터(m x 1 행렬)는 m 원소들의 단일 열 행렬
* 행 벡터(1 x m 행렬)은 m원소들의 단일 행 행렬.
* 리스트, 딕셔너리, ndarray 등 다양한 데이터로부터 생성
* 반대로 리스트, 딕셔너리, ndarray 등으로 변환될 수 있음

In [85]:
# 배열을 데이터프레임으로 변환
np.random.seed(0)
data = np.random.randint(100,200,size=(3,4))
print(data, type(data))

df = pd.DataFrame(data, index=['d1','d2','d3'],
                  columns = ['pd', 'sales', 'inv','salary'])
df

[[144 147 164 167]
 [167 109 183 121]
 [136 187 170 188]] <class 'numpy.ndarray'>


pd  sales  inv  salary
d1  144    147  164     167
d2  167    109  183     121
d3  136    187  170     188

In [86]:
print(df.pd, type(df.pd))

d1    144
d2    167
d3    136
Name: pd, dtype: int64 <class 'pandas.core.series.Series'>


In [87]:
df = pd.DataFrame(data, columns = ['pd','sales','inb','salary'])
df

pd  sales  inb  salary
0  144    147  164     167
1  167    109  183     121
2  136    187  170     188

#### Pandas의 iloc와 loc 메서드
DataFrame과 Series에서 데이터의 특정 위치나 라벨에 접근하기 위한 중요한 도구이며 두 메서드는 각각 고유한 용도를 가지고 있다.

- iloc (Integer Location)
  - 정수 인덱스 기반으로 데이터에 접근하는 메서드. 즉, DataFrame이나 Series의 특정 위치에 있는 데이터를 선택할 때 사용.
  - 슬라이싱 지원: Python 리스트와 유사하게 슬라이싱을 지원.
  - 양 끝점 포함하지 않음: 슬라이싱 시 끝점은 포함하지 않는다.
- loc (Label Location)
  - 라벨 인덱스 기반으로 데이터에 접근하는 메서드. 즉, DataFrame이나 Series의 라벨 이름을 사용하여 데이터에 접근.
  - 슬라이싱 지원: 라벨을 사용하여 슬라이싱을 지원.
  - 끝점 포함: 슬라이싱 시 끝점을 포함.

In [94]:
import pandas as pd

# 데이터프레임 생성
data = {
    'A': [1, 2, 3, 4],
    'B': [5, 6, 7, 8],
    'C': [9, 10, 11, 12]
}
df = pd.DataFrame(data)
print(df,'\n')
# 첫 번째 행, 두 번째 열의 값 선택
print(df.iloc[0,1]) # 출력 : 5

# 첫 번째부터 두 번쨰 행, 첫 번째부터 두 번째 열 선택
print(df.iloc[0:2, 0:2])

   A  B   C
0  1  5   9
1  2  6  10
2  3  7  11
3  4  8  12 

5
   A  B
0  1  5
1  2  6


In [95]:
import pandas as pd

# 데이터프레임 생성
data = {
    'A': [1, 2, 3, 4],
    'B': [5, 6, 7, 8],
    'C': [9, 10, 11, 12]
}
df = pd.DataFrame(data, index=['a','b','c','d'])
print(df,'\n')
# 인덱스 'a' 열 'B'의 값 선택
print(df.loc['a','B'])  # 출력 : 5

# 인덱스 'a'부터 'b', 열'A'부터 'B' 선택
print(df.loc['a':'b','A':'B'])

   A  B   C
a  1  5   9
b  2  6  10
c  3  7  11
d  4  8  12 

5
   A  B
a  1  5
b  2  6


In [182]:
# 배열을 데이터프레임으로 변환
np.random.seed(0)
data = np.random.randint(100,200,size=(3,4))
print(data, type(data))

df = pd.DataFrame(data, index=['d1','d2','d3'],
                  columns = ['pd', 'sales', 'inv','salary'])
print(df)
print(df,type(df))

[[144 147 164 167]
 [167 109 183 121]
 [136 187 170 188]] <class 'numpy.ndarray'>
     pd  sales  inv  salary
d1  144    147  164     167
d2  167    109  183     121
d3  136    187  170     188
     pd  sales  inv  salary
d1  144    147  164     167
d2  167    109  183     121
d3  136    187  170     188 <class 'pandas.core.frame.DataFrame'>


In [183]:
# pandas indexing : iloc 정수 인덱스, loc 이름 인덱스
print(df.iloc[1],'\n')
print(df.loc['d2'])

pd        167
sales     109
inv       183
salary    121
Name: d2, dtype: int64 

pd        167
sales     109
inv       183
salary    121
Name: d2, dtype: int64


In [184]:
print(df.iloc[1,:],'\n')
print(df.loc['d2',:])

pd        167
sales     109
inv       183
salary    121
Name: d2, dtype: int64 

pd        167
sales     109
inv       183
salary    121
Name: d2, dtype: int64


In [102]:
df

pd  sales  inv  salary
d1  144    147  164     167
d2  167    109  183     121
d3  136    187  170     188

In [101]:
# Q. iloc, loc를 사용하여 183을 출력하세요.
print(df.iloc[1,2],'\n')
print(df.loc['d2','inv'])

183 

183


In [103]:
df.loc['d3'] = 0
df

pd  sales  inv  salary
d1  144    147  164     167
d2  167    109  183     121
d3    0      0    0       0

In [104]:
df.loc['d4'] = 0
df

pd  sales  inv  salary
d1  144    147  164     167
d2  167    109  183     121
d3    0      0    0       0
d4    0      0    0       0

In [105]:
# loc는 추가가 되는데 iloc는 안됨
df.iloc[4] = 0
df

IndexError: iloc cannot enlarge its target object

In [106]:
df.loc[:,'profit'] = 10
df

pd  sales  inv  salary  profit
d1  144    147  164     167      10
d2  167    109  183     121      10
d3    0      0    0       0      10
d4    0      0    0       0      10

[파이썬random 함수]

In [107]:
import random
print(random.random(),'\n') # 0.0 <= x < 1.0 사이
print(random.randint(1,10),'\n') # 1에서 10사이의 정수중에서 난수 값 리턴
print(random.uniform(10,20), '\n') # min max 사이 float 리턴
print(random.randrange(10), '\n') # 지정 범위 int 리턴
print(random.choice([1,2,3,4,5]),'\n') # 리스트 내부에 있는 요소를 랜덤하게 선택
li = [1,2,3,4,5]
print(random.sample(li,3),'\n') # 리스트 요소를 중복이 안되게 리턴
random.shuffle(li) # 리스트 요소를 다시 섞어서 리턴
print(li)

0.46428688707459886 

9 

10.736424452635447 

7 

5 

[2, 4, 1] 

[4, 3, 1, 5, 2]


[numpy random 함수]

- np.random.seed : seed를 통한 난수 생성
- np.random.randint : 정수 난수 1개 생성
- np.random.rand : 0부터 1사이의 균일분포에서 난수 매트릭스 배열 생성
- np.random.randn : 가우시안 표준 정규분포에서 난수 매트릭스 배열 생성
- np.random.shuffle : 기존의 데이터의 순서 바꾸기
- np.random.choice : 기존 데이터에서 sampling

In [108]:
import numpy as np
print(np.random.randint(6), '\n') # 0 ~ 5까지 정수인 난수 1개
print(np.random.randint(1,20),'\n') # 1 ~ 19까지 정수인 난수 1개
print(np.random.randint(10, size=10), '\n') # 0 ~ 9까지 정수인 난수 10개
print(np.random.randint(10,20, size=10),'\n') # 10 ~ 19까지 정수인 난수 10개
print(np.random.randint(10,20, size=(3,5))) # 10 ~ 19까지 정수인 난수로 3행 5열 배열 생성

0 

13 

[1 6 7 7 8 1 5 9 8 9] 

[14 13 10 13 15 10 12 13 18 11] 

[[13 13 13 17 10]
 [11 19 19 10 14]
 [17 13 12 17 12]]


In [110]:
# id, gender, age, region
import numpy as np
import pandas as pd
id = np.arange(1,1001)
i1 = pd.Series(id)
gender = np.random.randint(2,size=1000)
g1 = pd.Series(gender)
age = np.random.randint(1,101,size=1000)
a1 = pd.Series(age)
region = np.random.randint(1,11,size=1000)
r1 = pd.Series(region)

df = pd.concat([i1,g1,a1,r1],axis=1)
df.rename(columns={0:'id',1:'gender',2:'age',3:'region'},inplace=True)  #inplace=True 기존 데이터 프레임 변경된 설정으로 덮어 씌운다
df.head()

id  gender  age  region
0   1       0   80      10
1   2       0   63       6
2   3       0   77       2
3   4       1   48       9
4   5       1   77       2

In [112]:
df.drop([0], axis=0, inplace=True)
df.head()

id  gender  age  region
1   2       0   63       6
2   3       0   77       2
3   4       1   48       9
4   5       1   77       2
5   6       0   22       8

- at은 라벨 기반 인덱싱을 사용. 단일 값을 접근할 때 loc 접근자 보다 빠르다.
- 여러 값을 동시에 접근하려면 loc 접근자를 사용

In [114]:
df.loc[5, 'id']

6

In [113]:
df.at[5, 'id']

6

In [115]:
df1 = df.drop(df.at[5,'id'])
df1.head(7)

id  gender  age  region
1   2       0   63       6
2   3       0   77       2
3   4       1   48       9
4   5       1   77       2
5   6       0   22       8
7   8       0   90       6
8   9       1   14       1

Task1_0527. 4개의 Series를 결합하여 데이터프레임을 생성하여 출력하세요.
- 출력한 데이터프레임에서 추출하고 싶은 5개의 데이터를 인덱싱하여 출력
- null값을 3개 추가
- null값의 개수를 확인하고 삭제
- 2개의 데이터를 수정
- 1개의 행을 삭제

In [193]:
import pandas as pd

data = {
    'name':['나홍인','정진아','넬','소지승','차승원','바나나차차','마조리카'],
    'age':[40,30,20,10,15,26,25],
    'addr':['경기도 수원','경기도 광교','경기도 널','경기도 널','경기도 영통','수원시 조원동','조원동 부자치킨'],
    'phone':['0421','3468','2378','9565','1234','4545','7890']
}
users = pd.DataFrame(data,index=(1,2,3,4,5,6,7))
users

name  age      addr phone
1    나홍인   40    경기도 수원  0421
2    정진아   30    경기도 광교  3468
3      넬   20     경기도 널  2378
4    소지승   10     경기도 널  9565
5    차승원   15    경기도 영통  1234
6  바나나차차   26   수원시 조원동  4545
7   마조리카   25  조원동 부자치킨  7890

In [116]:
# df1 = df[:]
df1 = df.copy()
df1.head()
# df1.tail(3)

id  gender  age  region
1   2       0   63       6
2   3       0   77       2
3   4       1   48       9
4   5       1   77       2
5   6       0   22       8

In [117]:
np.random.seed(0)
a = np.random.randint(1,5,size=(10,5))
print(a,type(a))

[[1 4 2 1 4]
 [4 4 4 2 4]
 [2 3 1 4 3]
 [1 1 1 3 2]
 [3 4 4 3 1]
 [2 2 2 2 1]
 [2 1 4 1 4]
 [2 3 4 4 1]
 [3 4 1 2 4]
 [2 4 4 3 4]] <class 'numpy.ndarray'>


In [119]:
# 2차원 리스트를 데이터 프레임으로 변환
list1 = a.tolist()
# print(list1.type(list))

df1=pd.DataFrame(list1, columns=['c1','c2,','c3','c4','c5'])
# df1 = pd.DataFrame(list1, columns=list('abcde'))
print(df1.head())

   c1  c2,  c3  c4  c5
0   1    4   2   1   4
1   4    4   4   2   4
2   2    3   1   4   3
3   1    1   1   3   2
4   3    4   4   3   1


In [122]:
# 데이터프레임을 배열, 리스트, 딕셔너리로 변환
ar = df1.values
print(ar,type(ar))
print()
li = ar.tolist()
print(li,type(li))
print()
dict = df1.to_dict('list')
print(dict,type(dict))

[[1 4 2 1 4]
 [4 4 4 2 4]
 [2 3 1 4 3]
 [1 1 1 3 2]
 [3 4 4 3 1]
 [2 2 2 2 1]
 [2 1 4 1 4]
 [2 3 4 4 1]
 [3 4 1 2 4]
 [2 4 4 3 4]] <class 'numpy.ndarray'>

[[1, 4, 2, 1, 4], [4, 4, 4, 2, 4], [2, 3, 1, 4, 3], [1, 1, 1, 3, 2], [3, 4, 4, 3, 1], [2, 2, 2, 2, 1], [2, 1, 4, 1, 4], [2, 3, 4, 4, 1], [3, 4, 1, 2, 4], [2, 4, 4, 3, 4]] <class 'list'>

{'c1': [1, 4, 2, 1, 3, 2, 2, 2, 3, 2], 'c2,': [4, 4, 3, 1, 4, 2, 1, 3, 4, 4], 'c3': [2, 4, 1, 1, 4, 2, 4, 4, 1, 4], 'c4': [1, 2, 4, 3, 3, 2, 1, 4, 2, 3], 'c5': [4, 4, 3, 2, 1, 1, 4, 1, 4, 4]} <class 'dict'>


Task2_0527. 학생별 성적 데이터셋으로 의미있게 데이터 셋을 수정하세요.(아래 사항 반영)
- S1 ~ S10은 평균 점수를 기준으로 1등급에서 10등급이고 등급간 점수 차는 5점
- 결시자가 국어 3명, 수학 2명 있음
- 영어, 수학의 평균 점수가 국어 대비 5점 낮음

In [123]:
import pandas as pd
import numpy as np
df = np.random.randint(1,5,size=(10,5))
df=pd.DataFrame(df,index=['s1','s2','s3','s4','s5','s6','s7','s8','s9','s10'],
               columns=['국어','영어','수학','과학','사회'])
df


국어  영어  수학  과학  사회
s1    1   2   2   2   4
s2    1   4   3   1   4
s3    4   3   4   3   4
s4    1   3   1   1   1
s5    2   2   3   1   1
s6    2   4   1   2   3
s7    3   4   1   2   2
s8    4   2   2   4   3
s9    4   4   3   3   4
s10   1   3   4   2   1

Task3_0527. df1에서 결측값 처리 후 딕셔너리, 리스트로 변환하여 출력하세요.

In [129]:
df1 = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Math": [85, np.nan, 88, 90, 76],
    "English": [92, 85, 89, np.nan, 80],
    "Science": [78, 90, 95, 85, 89],
    "History": [88, 92, 85, 91, np.nan]
})
df1.fillna(0)
li = df1.values
li1 = li.tolist()
print(li1)

[['Alice', 85.0, 92.0, 78, 88.0], ['Bob', nan, 85.0, 90, 92.0], ['Charlie', 88.0, 89.0, 95, 85.0], ['David', 90.0, nan, 85, 91.0], ['Eve', 76.0, 80.0, 89, nan]]


Task4_0527. df2에서 아래와 같이 데이터 필터링 및 정렬 후 배열, 딕셔너리, 리스트로 변환하여 출력하세요.
- Math 점수가 80 이상인 학생만 선택
- English 점수를 기준으로 내림차순 정렬

In [157]:
df2 = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Math": [85, 79, 88, 90, 76],
    "English": [92, 85, 89, 93, 80],
    "Science": [78, 90, 95, 85, 89],
    "History": [88, 92, 85, 91, 84]
})
li = df2[df2["Math"] > 80]
li1 = li.sort_values("English",ascending=False)

li2 = li1.values
list1 = li2.tolist()
print(list1)


[['David', 90, 93, 85, 91], ['Alice', 85, 92, 78, 88], ['Charlie', 88, 89, 95, 85]]


Task5_0527. df3에서 각 학생의 평균 점수 계산 후 배열, 딕셔너리, 리스트로 변환하여 출력하세요.

In [158]:
df3 = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Alice", "Bob", "Charlie", "David", "Eve"],
    "Subject": ["Math", "Math", "Math", "Math", "Math", "English", "English", "English", "English", "English"],
    "Score": [85, 79, 88, 90, 76, 92, 85, 89, 93, 80]
})
df3

Name  Subject  Score
0    Alice     Math     85
1      Bob     Math     79
2  Charlie     Math     88
3    David     Math     90
4      Eve     Math     76
5    Alice  English     92
6      Bob  English     85
7  Charlie  English     89
8    David  English     93
9      Eve  English     80

Task6_0527. df4에서 특정 열의 데이터 타입을 변환한 후 변환된 타입을 확인하세요.

In [164]:
df4 = pd.DataFrame({
    'A': ['1', '2', '3', '4'],
    'B': ['5.1', '6.2', '7.3', '8.4'],
    'C': ['2021-01-01', '2021-02-01', '2021-03-01', '2021-04-01']
})
df4

A    B           C
0  1  5.1  2021-01-01
1  2  6.2  2021-02-01
2  3  7.3  2021-03-01
3  4  8.4  2021-04-01

Task7_0527. df5에서 나이가 25 이상인 행을 출력하세요.

In [163]:
df5 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [24, 27, 22, 32, 29],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
})
age = df5[df5['Age'] >=25]
age

Name  Age         City
1    Bob   27  Los Angeles
3  David   32      Houston
4    Eve   29      Phoenix