<a href="https://colab.research.google.com/github/sojiseung/sjs0424/blob/main/m3_%EB%B6%84%EC%84%9D_%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC/05_28_%EA%B3%BC%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Contetnts
- 기초 연산
- 그룹 연산 : 집계, 변환, 필터링, 그룹매핑
- 함수 매핑 : map, apply, applymap
- Pivot

In [1]:
import pandas as pd
import numpy as np
st1 = pd.Series({'국어':100,'영어':80,'수학':90})
st2 = pd.Series({'국어':80,'영어':90,'수학':80})

print(st1, '\n')
print(st2)

국어    100
영어     80
수학     90
dtype: int64 

국어    80
영어    90
수학    80
dtype: int64


In [3]:
pd.DataFrame(st1+st2)

0
국어  180
영어  170
수학  170

In [4]:
# 두 학생의 과목별 점수로 사칙연산 수행
add = st1 + st2
sub = st1 - st2
mul = st1 * st2
div = round((st1 / st2),2)
df = pd.concat([add,sub,mul,div],axis=1)
print(df)

      0   1     2     3
국어  180  20  8000  1.25
영어  170 -10  7200  0.89
수학  170  10  7200  1.12


In [10]:
df = pd.concat([add,sub,mul,div],axis=1)
df.columns = ['덧셈','뺼셈','곱셈','나눈셈']
# df.index.name = '과목'
df

덧셈  뺼셈    곱셈   나눈셈
국어  180  20  8000  1.25
영어  170 -10  7200  0.89
수학  170  10  7200  1.12

In [11]:
result = pd.DataFrame([add,sub,mul,div])
result

국어       영어       수학
0   180.00   170.00   170.00
1    20.00   -10.00    10.00
2  8000.00  7200.00  7200.00
3     1.25     0.89     1.12

In [12]:
result = pd.DataFrame([add,sub,mul,div],index=['덧셈','뺼셈','곱셈','나눈셈'])
result

국어       영어       수학
덧셈    180.00   170.00   170.00
뺼셈     20.00   -10.00    10.00
곱셈   8000.00  7200.00  7200.00
나눈셈     1.25     0.89     1.12

In [53]:
st1 = pd.Series({'국어':np.nan,'영어':80,'수학':90})
st2 = pd.Series({'수학':80,'국어':90})


add = st1 + st2
sub = st1 - st2
mul = st1 * st2
div = round((st1 / st2),2)

result = pd.DataFrame([add,sub,mul,div],
                     index=['덧셈','뺄셈','곱셈','나눗셈'])
result

국어       수학  영어
덧셈   90.0   170.00 NaN
뺄셈    NaN    10.00 NaN
곱셈    NaN  7200.00 NaN
나눗셈   NaN     1.12 NaN

Q. Null값을 0으로 변경하여 결과를 출력하세요.

In [54]:
st1 = pd.Series({'국어':np.nan,'영어':80,'수학':90})
st2 = pd.Series({'수학':80,'국어':90})



ad = st1.add(st2,fill_value=0)
su = st1.sub(st2,fill_value=0)
mu = st1.mul(st2,fill_value=0)
di = st1.div(st2,fill_value=0)
df = pd.DataFrame([ad,su,mu,di],
                     index=['덧셈','뺄셈','곱셈','나눗셈'])
df

국어        수학    영어
덧셈   90.0   170.000  80.0
뺄셈  -90.0    10.000  80.0
곱셈    0.0  7200.000   0.0
나눗셈   0.0     1.125   inf

In [26]:
np.arange(12.).reshape((3,4))

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [30]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)), columns=list('abcd'))
print(df1,'\n')
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)), columns=list('abcde'))
print(df2)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0 

      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0


In [31]:
df2.loc[1,'b'] = np.nan
print(df1)
print(df2)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0
      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0


In [32]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

Task1_0528. 연산메소드 이용 및 NaN 값을 0으로 대체 후 사칙연산을 수행한 후 결과를 출력하세요.

In [57]:
st1 = pd.Series({'A':45,'B':np.nan,'C':76})
st2 = pd.Series({'A':75,'B':90})

add = st1.add(st2,fill_value=0)
sub = st1.sub(st2,fill_value=0)
mul = st1.mul(st2,fill_value=0)
div = st1.div(st2,fill_value=0)

t_df1 = pd.DataFrame([add,sub,mul,div],
                     index=['덧셈','뺄셈','곱셈','나눗셈'])
t_df1

A     B     C
덧셈    120.0  90.0  76.0
뺄셈    -30.0 -90.0  76.0
곱셈   3375.0   0.0   0.0
나눗셈     0.6   0.0   inf

In [34]:
# 계산인자를 뒤집어 계산
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [35]:
print(df1)
df1.rsub(1)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0


a    b    c     d
0  1.0  0.0 -1.0  -2.0
1 -3.0 -4.0 -5.0  -6.0
2 -7.0 -8.0 -9.0 -10.0

In [36]:
print(df1)
df1.radd(1)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0


a     b     c     d
0  1.0   2.0   3.0   4.0
1  5.0   6.0   7.0   8.0
2  9.0  10.0  11.0  12.0

In [37]:
print(df1)
df1.rmul(10)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0


a     b      c      d
0   0.0  10.0   20.0   30.0
1  40.0  50.0   60.0   70.0
2  80.0  90.0  100.0  110.0

In [38]:
# 배열의 연산
arr = np.arange(12.).reshape(3,4)
print(arr,'\n')
print(arr[0])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[0 1 2 3]


In [39]:
# broadcasting
arr - arr[0]

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [40]:
# DataFrame과 Series간 연산
frame = pd.DataFrame(np.arange(12.).reshape(4,3),columns=list('bde'),
                    index = ['Utah','Ohio','Texas','Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [41]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [43]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [44]:
a = np.arange(6).reshape(1,6)
a

array([[0, 1, 2, 3, 4, 5]])

In [45]:
a= np.arange(6).reshape(6,)
a

array([0, 1, 2, 3, 4, 5])

Task2_0528. 주어진 DataFrame의 N열에서 Series s값을 빼고 결과를 새로운 열 O에 저장 후 출력하세요.

In [58]:
import pandas as pd

# 데이터프레임 생성
df = pd.DataFrame({
    "M": [15, 25, 35, 45, 55],
    "N": [100, 200, 300, 400, 500]
})
print(df,'\n')
# Series 생성
s = pd.Series([5, 10, 15, 20, 25])

    M    N
0  15  100
1  25  200
2  35  300
3  45  400
4  55  500 



In [61]:
o = df["N"]-s
df["O"] = o
df

M    N    O
0  15  100   95
1  25  200  190
2  35  300  285
3  45  400  380
4  55  500  475

Task3_0528. 주어진 DataFrame의 여러 열에 대해 각기 다른 Series를 더하고, 결과를 새로운 DataFrame으로 반환한 후 각 행의 합계를 계산하여 새로운 열에 추가하여 출력하세요.

In [83]:
import pandas as pd

# 데이터프레임 생성
df = pd.DataFrame({
    "A": [1, 2, 3, 4, 5],
    "B": [10, 20, 30, 40, 50],
    "C": [100, 200, 300, 400, 500]
})

# Series 생성
s1 = pd.Series([5, 5, 5, 5, 5])
s2 = pd.Series([10, 10, 10, 10, 10])
s3 = pd.Series([15, 15, 15, 15, 15])
df

A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [86]:
new_df = pd.DataFrame(
    {'A':(df['A']+s1),'B':(df['B']+s2),'C':(df['C']+s3)}
)
new_df['합계'] = new_df['A']+new_df['B']+new_df['C']
new_df

A   B    C   합계
0   6  20  115  141
1   7  30  215  252
2   8  40  315  363
3   9  50  415  474
4  10  60  515  585

#### 그룹 연산
* 복잡한 데이터를 어떤 기준에 따라 여러 그룹으로 나누어서 관찰할 수 있으며 이런 방식으로 분할 처리하는 것을 그룹 연산이라 함
* 그룹 연산은 데이터를 집계, 변환, 필터링하는데 효율적이며 판다스 groupby() 메소드를 사용함
* 그룹 객체 만들기(분할)
* 그룹 연산 메소드(적용-결합)

In [51]:
import pandas as pd
import seaborn as sns

# titanic 데이터셋에서 age, sex 등 5개 열을 선택하여 데이터프레임 만들기
titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age','sex','class','fare','survived']]
# df = titanic[:, ['age','sex','class','fare','survived']]
print('승객 수 : ', len(df))
print(df.head())

승객 수 :  891
    age     sex  class     fare  survived
0  22.0    male  Third   7.2500         0
1  38.0  female  First  71.2833         1
2  26.0  female  Third   7.9250         1
3  35.0  female  First  53.1000         1
4  35.0    male  Third   8.0500         0


In [52]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


Task4_0528. df에서 세 열의 값을 더하여 새로운 컬럼을 생성한 후 출력하세요.

In [63]:
import pandas as pd

# 데이터프레임 생성
df = pd.DataFrame({
    "A": [10, 20, 30, 40, 50],
    "B": [1, 2, 3, 4, 5],
    "C": [5, 10, 15, 20, 25],
    "D": [3, 6, 9, 12, 15],
    "E": [2, 4, 6, 8, 10]
})
df["F"] = df["A"]+ df["C"]+df["E"]
df

A  B   C   D   E   F
0  10  1   5   3   2  17
1  20  2  10   6   4  34
2  30  3  15   9   6  51
3  40  4  20  12   8  68
4  50  5  25  15  10  85

Task5_0528. df에서 세 열의 값을 평균하여 새로운 컬럼을 생성 후 출력하세요.

In [93]:
import pandas as pd

# 데이터프레임 생성
df = pd.DataFrame({
    "A": [100, 200, 300, 400, 500],
    "B": [10, 20, 30, 40, 50],
    "C": [1, 2, 3, 4, 5],
    "D": [7, 8, 9, 10, 11],
    "E": [3, 6, 9, 12, 15]
})
df["F"] = round((df["A"]+ df["C"]+df["E"])/3,2)
df

A   B  C   D   E       F
0  100  10  1   7   3   34.67
1  200  20  2   8   6   69.33
2  300  30  3   9   9  104.00
3  400  40  4  10  12  138.67
4  500  50  5  11  15  173.33

Task6_0528. df에서 두 개의 열을 더한 값이 다른 한 개의 열보다 큰 경우에는 1, 작은 경우에는 0으로 값을 정하는 새로운 열을 생성한 후 출력하세요.

In [ ]:
import pandas as pd

# 데이터프레임 생성
df = pd.DataFrame({
    "A": [2, 3, 4, 5, 6],
    "B": [1, 2, 3, 4, 5],
    "C": [3, 4, 5, 6, 7],
    "D": [8, 9, 10, 11, 12],
    "E": [10, 20, 30, 40, 50]
})